%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\bo.bekkouche\Documents\code\NMDAwave\calciumWaveModels-9.5\extra_analysis\ParamDepend_Graphs.xlsx
%    Worksheet: Speed RyR
%
% Auto-generated by MATLAB on 13-May-2023 12:24:08

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 24);

% Specify sheet and range
opts.Sheet = "Speed RyR";
opts.DataRange = "A2:X10";

% Specify column names and types
opts.VariableNames = ["rlxCeCtl", "Vel", "rle", "Vel1", "fCac", "Vel2", "fCae", "Vel3", "fInP3", "Vel4", "Rp_PM", "Vel5", "RpS", "Vel6", "kbCf", "Vel7", "rmIf", "Vel8", "kiPI", "Vel9", "rIg", "Vel10", "Ce0", "Vel11"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
speed_ryr = readtable("C:\Users\bo.bekkouche\Documents\code\NMDAwave\calciumWaveModels-9.5\extra_analysis\ParamDepend_Graphs.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts


